GET http://127.0.0.1:8080/ui/v1/api/greetings
Accept: application/json
Content-Type: application/json

###
GET http://127.0.0.1:8080/ui/v1/api/names
Accept: application/json
Content-Type: application/json

###
